# https://github.com/actions/labeler

# Add label to the PRs changing files under tools/llm_bench/
llm_bench:
- changed-files:
  - any-glob-to-any-file:
    - 'tools/llm_bench/**'
    - '.github/workflows/llm_bench-python.yml'
# Add label to the PRs changing files under tools/who_what_benchmark/
WWB:
- changed-files:
  - any-glob-to-any-file:
    - 'tools/who_what_benchmark/**'
