[project]
name = "openvino-genai"
version = "2024.5.0.0"
description = "Python bindings for https://github.com/openvinotoolkit/openvino.genai"
requires-python = ">=3.8"
readme = {file = "src/README.md", content-type="text/markdown"}
license = {text = "OSI Approved :: Apache Software License"}
authors = [
    { name = "OpenVINO Developers", email = "openvino@intel.com" },
]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "openvino_tokenizers~=2024.5.0.0.dev"
]

[tool.black]
exclude = '''
(
  README\.md|
  SECURITY\.md|
  LICENSE|
  third-party-programs\.txt|
  tests/python_tests/README\.md|
  llm_bench/python/README\.md|
  llm_bench/python/doc/IMAGE_GEN\.md|
  llm_bench/python/doc/NOTES\.md|
  llm_bench/python/who_what_benchmark/README\.md|
  samples/cpp/beam_search_casual_lm/README\.md|
  samples/cpp/benchmark_genai/README\.md|
  samples/cpp/chat_sample/README\.md|
  samples/cpp/greedy_casual_lm/README\.md|
  samples/cpp/multinomial_casual_lm/README\.md|
  samples/cpp/prompt_lookup_decoding_lm/README\.md|
  samples/cpp/speculative_decoding_lm/README\.md|
  samples/cpp/stable_diffusion/README\.md|
  samples/cpp/whisper_speech_recognition/README\.md|
  samples/python/beam_search_casual_lm/README\.md|
  samples/python/benchmark_genai/README\.md|
  samples/python/chat_sample/README\.md|
  samples/python/greedy_casual_lm/README\.md|
  samples/python/multinomial_casual_lm/README\.md|
  samples/python/whisper_speech_recognition/README\.md|
  src/README\.md|
  src/docs/BUILD\.md|
  src/docs/DOCKER\.md|
  src/docs/SUPPORTED_MODELS\.md
)
'''

[tool.py-build-cmake.module]
directory = "src/python"

[tool.py-build-cmake.sdist]
exclude = ["llm_bench", "samples", "tests", "thirdparty"]

[tool.py-build-cmake.cmake]
minimum_version = "3.23"
build_type = "Release"
config = ["Release"]
find_python3 = true
build_args = ["--parallel", "--target", "py_generate_pipeline"]
install_args = ["--strip"]
install_components = ["wheel_genai"]

[build-system]
requires = [
    "py-build-cmake@git+https://github.com/tttapa/py-build-cmake@7ab73da351c7140f06d727a8705bece4cf544cd9",
    "cmake~=3.23"
]
build-backend = "py_build_cmake.build"

[tool.pytest.ini_options]
markers = [
    "nightly",
    "precommit: (deselect with '-m \"precommit\"')",
]
