name: python -m bandit --recursive --configfile bandit.yml .
on:
  pull_request:
    paths-ignore:
      - 'thirdparty'
      - '**.md'
permissions: read-all  # Required by https://github.com/ossf/scorecard/blob/e23b8ad91fd6a64a0a971ca4fc0a4d1650725615/docs/checks.md#token-permissions
jobs:
  bandit:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python -m pip install bandit
      - run: python -m bandit --recursive --configfile bandit.yml .
