name: casual_lm_cpp
on:
  pull_request:
    paths:
      - text_generation/casual_lm/cpp/**
      - '!text_generation/casual_lm/cpp/README.md'
      - thirdparty/openvino_contrib
      - .github/workflows/casual_lm_cpp.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  casual_lm_cpp:
    runs-on: ubuntu-20.04-8-cores
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: ./text_generation/casual_lm/cpp/set_up_and_run.sh
