# https://github.com/actions/labeler
name: label PRs

on:
  pull_request_target:
    types: [opened]
    paths:
      - llm_bench/python/**
      - .github/workflows/llm_bench-python.yml

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/labeler@v5
      with:
        configuration-path: '.github/label_config.yml'
