name: lcm_dreamshaper
on:
  pull_request:
    paths:
      - image_generation/lcm_dreamshaper_v7/cpp/src/**
      - .github/workflows/lcm_dreamshaper_v7_cpp.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lcm_dreamshaper_v7_cpp:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: ./image_generation/lcm_dreamshaper_v7/cpp/set_up_and_run.sh
