name: lcm_dreamshaper
on:
  pull_request:
    paths:
      - image_generation/lcm_dreamshaper_v7/cpp/**
      - image_generation/common/**
      - .github/workflows/lcm_dreamshaper_cpp.yml
      - thirdparty/openvino_contrib
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lcm_dreamshaper_v7_cpp-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Initialize OpenVINO
        run: |
          mkdir openvino
          curl https://storage.openvinotoolkit.org/repositories/openvino/packages/nightly/2024.0.0-14004-a240ae8fadd/l_openvino_toolkit_ubuntu20_2024.0.0.dev20240116_x86_64.tgz | tar --directory ./openvino/ --strip-components 1 -xz
          sudo ./openvino/install_dependencies/install_openvino_dependencies.sh
      - name: Download / convert a model / tokenizer
        run: |
          source ./openvino/setupvars.sh
          cd ./image_generation/lcm_dreamshaper_v7/cpp/scripts/
          python -m pip install -U pip
          python -m pip install -r ./requirements.txt
          python -m pip install ../../../../thirdparty/openvino_contrib/modules/custom_operations/
          python convert_model.py -lcm "SimianLuo/LCM_Dreamshaper_v7" -t "FP16"
      - name: Build app
        run: |
          source ./openvino/setupvars.sh
          cd ./image_generation/lcm_dreamshaper_v7/cpp/
          cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build/
          cmake --build ./build/ --config Release --parallel
      - name: Run app
        run: |
          source ./openvino/setupvars.sh
          cd ./image_generation/lcm_dreamshaper_v7/cpp/build/
          ./lcm_dreamshaper
  lcm_dreamshaper_v7_cpp-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - uses: actions/setup-python@v4
          with:
            python-version: 3.8
        - name: Initialize OpenVINO
          shell: cmd
          run: |
            curl --output ov.zip https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.3/windows/w_openvino_toolkit_windows_2023.3.0.13775.ceeafaf64f3_x86_64.zip
            unzip ov.zip
        - name: Download / convert a model / tokenizer
          shell: cmd
          run: |
            call w_openvino_toolkit_windows_2023.3.0.13775.ceeafaf64f3_x86_64/setupvars.bat
            cd ./image_generation/lcm_dreamshaper_v7/cpp/scripts/
            python -m pip install -r ./requirements.txt
            python -m pip install ../../../../thirdparty/openvino_contrib/modules/custom_operations/
            python convert_model.py -lcm "SimianLuo/LCM_Dreamshaper_v7" -t "FP16"
        - name: Build app
          shell: cmd
          run: |
            call w_openvino_toolkit_windows_2023.3.0.13775.ceeafaf64f3_x86_64/setupvars.bat
            cd ./image_generation/lcm_dreamshaper_v7/cpp/
            cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build/
            cmake --build ./build/ --config Release --parallel
        - name: Run app
          shell: cmd
          run: |
            call w_openvino_toolkit_windows_2023.3.0.13775.ceeafaf64f3_x86_64/setupvars.bat
            cd ./image_generation/lcm_dreamshaper_v7/cpp/build/
            call "./Release/lcm_dreamshaper.exe"
