name: llm-cpp
on:
  pull_request:
    paths:
      - llm/cpp/**
      - '!llm/cpp/README.md'
      - .github/workflows/llm.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  llm-cpp:
    runs-on: ubuntu-20.04-8-cores
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cpu llm/cpp/thirdparty/openvino_contrib/modules/custom_operations/user_ie_extensions/tokenizer/python/[transformers] onnx git+https://github.com/huggingface/optimum-intel.git &
          mkdir ov/
          curl https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.1/linux/l_openvino_toolkit_ubuntu20_2023.1.0.12185.47b736f63ed_x86_64.tgz | tar --directory ov/ --strip-components 1 -xz
          sudo ov/install_dependencies/install_openvino_dependencies.sh
          wait
      - uses: actions/cache@v3
        id: cache
        with:
          path: cache
          key: cache
      - name: Download, convert and build
        run: |
          source ov/setupvars.sh
          optimum-cli export openvino -m openlm-research/open_llama_3b_v2 --cache_dir cache/optimum/ open_llama_3b_v2/ &
          mkdir build/
          cd build/
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-Werror ../llm/cpp
          cmake --build . --config Release -j
          wait
      - name: Convert and run llm
        run: |
          source ov/setupvars.sh
          python llm/cpp/convert_tokenizers.py build/thirdparty/openvino_contrib/modules/custom_operations/user_ie_extensions/libuser_ov_extensions.so open_llama_3b_v2/
          ./build/llm open_llama_3b_v2/openvino_model.xml tokenizer.xml detokenizer.xml "return 0"
