name: llm-cpp
on:
  pull_request:
    paths:
      - llm/cpp/**
      - .github/workflows/llm.yml
      - thirdparty/**
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  llm-cpp:
    runs-on: ubuntu-20.04-8-cores
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: llm/cpp/set_up_and_run.sh
