name: stable_diffusion_1_5_cpp
on:
  pull_request:
    paths:
      - image_generation/stable_diffusion_1_5/cpp/**
      - image_generation/stable_diffusion_1_5/common/**
      - .github/workflows/stable_diffusion_1_5_cpp.yml
      - thirdparty/openvino_contrib
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  stable_diffusion_1_5_cpp:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: ./image_generation/stable_diffusion_1_5/cpp/set_up_and_run.sh
